# Site settings
title: Growing Pains
email: marffin@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Grow more, suffer less
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://hellmage.github.io" # the base hostname & protocol for your site
twitter_username:
github_username: hellmage

# Build settings
markdown: kramdown
highlighter: pygments
